export const videoContents = [
  {
    id: 1,
    thumbnail: "src/assets/content-section/html-tutor.webp",
    channelProfile: "src/assets/content-section/unnamed.jpg",
    videoTitle: "HTML & CSS Full Course - Beginner to Pro",
    channelName: "SuperSimpleDev",
    detail: "5.3M views : 1 year ago",
  },
  {
    id: 2,
    thumbnail: "src/assets/content-section/thumb2.webp",
    channelProfile: "src/assets/content-section/channel2.jpg",
    videoTitle:
      "여우야 - 설인아 [더 시즌즈-박재범의 드라이브] | KBS 230305 방송",
    channelName: "KBS Kpop",
    detail: "3.2M views : 4 months ago",
  },
  {
    id: 3,
    thumbnail: "src/assets/content-section/thumb3.webp",
    channelProfile: "src/assets/content-section/channel3.jpg",
    videoTitle: "Hotel (Ep. 2) | Awkward Puppets",
    channelName: "Awkward Puppets",
    detail: "209K views : 2 days ago",
  },
  {
    id: 4,
    thumbnail: "src/assets/content-section/thumb4.jpg",
    channelProfile: "src/assets/content-section/channel4.jpg",
    videoTitle: "Avenged Sevenfold - So Far Away (Official Music Video)",
    channelName: "The Pit",
    detail: "26M views : 12 years ago",
  },
  {
    id: 5,
    thumbnail: "src/assets/content-section/thumb5.jpg",
    channelProfile: "src/assets/content-section/channel5.jpg",
    videoTitle: "改编版的《错位时空》绝了，比原版更有生命力，看我中华盛世!",
    channelName: "EDM Music One Hour",
    detail: "409K views : 2 years ago",
  },
  {
    id: 6,
    thumbnail: "src/assets/content-section/thumb6.webp",
    channelProfile: "src/assets/content-section/channel6.jpg",
    videoTitle: "50 Entrepreneurs share priceless advice",
    channelName: "Blockshelf",
    detail: "4.1M views : 8 years ago",
  },
];
